import { PermissionSubject } from '@/lib/permissions'

/**
 * What the workshop chat's scoped views expose, table by table.
 *
 * Columns are listed rather than taken with `SELECT *` so that a column the
 * app treats as a secret never reaches the model: `publicToken` is a live
 * share link on invoices, quotes and inspections, `issuedData` is the frozen
 * invoice, `telegramChatId` identifies a customer's chat. The lists are
 * checked against the Prisma schema by a test, so a renamed column fails the
 * suite instead of failing the view at runtime.
 *
 * Each table also names the permission a role needs before the model may
 * read it, mirroring what the pages themselves require.
 */

/** Columns deliberately kept from the model, wherever they occur. */
export const HIDDEN_COLUMNS: readonly string[] = [
  'publicToken',
  'issuedData',
  'editUnlockedById',
  'createdById',
  'concernId',
  'telegramChatId',
]

export const TABLE_COLUMNS: Readonly<Record<string, readonly string[]>> = {
  vehicles: [
    'id',
    'make',
    'model',
    'year',
    'vin',
    'licensePlate',
    'color',
    'mileage',
    'fuelType',
    'transmission',
    'engineSize',
    'engineCode',
    'purchaseDate',
    'purchasePrice',
    'imageUrl',
    'isArchived',
    'archiveReason',
    'soldReportedAt',
    'maintenanceDismissed',
    'maintenanceDismissedAt',
    'createdAt',
    'updatedAt',
    'userId',
    'organizationId',
    'customerId',
    'importBatchId',
  ],
  service_records: [
    'id',
    'title',
    'description',
    'type',
    'status',
    // The workshop's own status under that stage, and when it was chosen.
    'customStatusId',
    'customStatusSince',
    'cost',
    'mileage',
    'serviceDate',
    'startDateTime',
    'endDateTime',
    'promisedAt',
    'shopName',
    'techName',
    'parts',
    'laborHours',
    'diagnosticNotes',
    'invoiceNotes',
    'subtotal',
    'taxRate',
    'taxAmount',
    'taxInclusive',
    'taxComponents',
    'totalAmount',
    'invoiceNumber',
    'invoiceDate',
    'invoiceDueDate',
    'discountType',
    'discountValue',
    'discountAmount',
    'manuallyPaid',
    'warrantyStatus',
    'warrantyMonths',
    'warrantyMileage',
    'warrantyExpiresAt',
    'warrantyNotes',
    'sharedAt',
    'viewCount',
    'lastViewedAt',
    'createdAt',
    'updatedAt',
    'sentAt',
    'designId',
    'issuedAt',
    'issuedDesignSnapshotId',
    'issuedLogoSnapshotId',
    'bookingSource',
    'editUnlockedAt',
    'tireSetId',
    'vehicleId',
    'customerId',
    'inspectionId',
    'organizationId',
    'technicianId',
    'workBayId',
    'sortOrder',
    'importBatchId',
  ],
  service_parts: [
    'id',
    'partNumber',
    'name',
    'quantity',
    'unit',
    'unitPrice',
    'total',
    'unitCost',
    'markupPercent',
    'inventoryPartId',
    'serviceRecordId',
  ],
  service_labor: ['id', 'description', 'hours', 'rate', 'total', 'pricingType', 'serviceRecordId'],
  service_attachments: [
    'id',
    'fileName',
    'fileUrl',
    'fileType',
    'fileSize',
    'category',
    'description',
    'includeInInvoice',
    'createdAt',
    'serviceRecordId',
  ],
  payments: [
    'id',
    'amount',
    'date',
    'method',
    'note',
    'provider',
    'externalId',
    'createdAt',
    'updatedAt',
    'serviceRecordId',
  ],
  customers: [
    'id',
    'customerNumber',
    'name',
    'email',
    'phone',
    'address',
    'company',
    'taxId',
    'taxExempt',
    'reminderOptOut',
    'notes',
    'createdAt',
    'updatedAt',
    'userId',
    'organizationId',
    'invoiceDesignId',
    'importBatchId',
  ],
  reminders: [
    'id',
    'title',
    'description',
    'dueDate',
    'hasDueTime',
    'dueMileage',
    'isCompleted',
    'notifyInApp',
    'notifyEmail',
    'notifiedAt',
    'createdAt',
    'updatedAt',
    'vehicleId',
    'customerId',
    'organizationId',
  ],
  quotes: [
    'id',
    'quoteNumber',
    'title',
    'description',
    'status',
    'validUntil',
    'subtotal',
    'taxRate',
    'taxAmount',
    'taxInclusive',
    'taxComponents',
    'discountType',
    'discountValue',
    'discountAmount',
    'totalAmount',
    'notes',
    'warrantyStatus',
    'warrantyMonths',
    'warrantyMileage',
    'warrantyNotes',
    'sharedAt',
    'viewCount',
    'lastViewedAt',
    'customerMessage',
    'convertedToId',
    'createdAt',
    'updatedAt',
    'sentAt',
    'responseDismissedAt',
    'editUnlockedAt',
    'userId',
    'organizationId',
    'customerId',
    'tireSetId',
    'vehicleId',
    'inspectionId',
  ],
  quote_parts: [
    'id',
    'partNumber',
    'name',
    'quantity',
    'unit',
    'unitCost',
    'markupPercent',
    'unitPrice',
    'total',
    'excluded',
    'inventoryPartId',
    'quoteId',
  ],
  quote_labor: [
    'id',
    'description',
    'hours',
    'rate',
    'total',
    'pricingType',
    'excluded',
    'quoteId',
  ],
  quote_attachments: [
    'id',
    'fileName',
    'fileUrl',
    'fileType',
    'fileSize',
    'category',
    'description',
    'includeInInvoice',
    'createdAt',
    'quoteId',
  ],
  inventory_parts: [
    'id',
    'partNumber',
    'barcode',
    'name',
    'description',
    'category',
    'quantity',
    'minQuantity',
    'unit',
    'unitCost',
    'sellPrice',
    'supplier',
    'supplierPhone',
    'supplierEmail',
    'supplierUrl',
    'imageUrl',
    'location',
    'isArchived',
    'lowStockAlertedAt',
    'createdAt',
    'updatedAt',
    'userId',
    'organizationId',
  ],
  notes: ['id', 'title', 'content', 'isPinned', 'createdAt', 'updatedAt', 'vehicleId'],
  fuel_logs: [
    'id',
    'date',
    'mileage',
    'gallons',
    'pricePerGallon',
    'totalCost',
    'isFillUp',
    'station',
    'notes',
    'createdAt',
    'updatedAt',
    'vehicleId',
  ],
  technicians: [
    'id',
    'name',
    'color',
    'isActive',
    'sortOrder',
    'dailyCapacity',
    'skills',
    'userId',
    'organizationId',
    'createdAt',
    'updatedAt',
  ],
  inspections: [
    'id',
    'status',
    'mileage',
    'notes',
    'startDateTime',
    'endDateTime',
    'completedAt',
    'createdAt',
    'updatedAt',
    'vehicleId',
    'templateId',
    'technicianId',
    'workBayId',
    'sortOrder',
    'severityScale',
    'country',
    'vehicleCategory',
    'nextTestDue',
    'certificateNumber',
    'inspectorName',
    'testLocation',
    'organizationId',
    'importBatchId',
  ],
  inspection_items: [
    'id',
    'name',
    'section',
    'sortOrder',
    'condition',
    'notes',
    'imageUrls',
    'description',
    'code',
    'sectionCode',
    'inputType',
    'unit',
    'minValue',
    'maxValue',
    'choices',
    'required',
    'photoRequired',
    'defaultSeverity',
    'defectSuggestions',
    'measuredValue',
    'textValue',
    'inspectionId',
  ],
  recurring_invoices: [
    'id',
    'title',
    'description',
    'frequency',
    'nextRunDate',
    'endDate',
    'isActive',
    'lastRunAt',
    'runCount',
    'type',
    'cost',
    'taxRate',
    'taxInclusive',
    'taxComponents',
    'invoiceNotes',
    'vehicleId',
    'createdAt',
    'updatedAt',
  ],
  recurring_parts: ['id', 'name', 'partNumber', 'quantity', 'unitPrice', 'recurringInvoiceId'],
  recurring_labor: ['id', 'description', 'hours', 'rate', 'pricingType', 'recurringInvoiceId'],
  notifications: [
    'id',
    'type',
    'title',
    'message',
    'entityType',
    'entityId',
    'entityUrl',
    'read',
    'organizationId',
    'createdAt',
  ],
  sms_messages: [
    'id',
    'direction',
    'fromNumber',
    'toNumber',
    'body',
    'status',
    'providerMsgId',
    'errorMessage',
    'relatedEntityType',
    'relatedEntityId',
    'readAt',
    'createdAt',
    'updatedAt',
    'organizationId',
    'customerId',
  ],
  inspection_quote_requests: [
    'id',
    'status',
    'message',
    'selectedItemIds',
    'createdAt',
    'inspectionId',
    'organizationId',
  ],
}

/** The permission that lets a role read each table through the chat. */
export const TABLE_SUBJECTS: Readonly<Record<string, PermissionSubject>> = {
  vehicles: PermissionSubject.VEHICLES,
  notes: PermissionSubject.VEHICLES,
  fuel_logs: PermissionSubject.VEHICLES,
  reminders: PermissionSubject.VEHICLES,
  customers: PermissionSubject.CUSTOMERS,
  sms_messages: PermissionSubject.CUSTOMERS,
  service_records: PermissionSubject.WORK_ORDERS,
  service_parts: PermissionSubject.WORK_ORDERS,
  service_labor: PermissionSubject.WORK_ORDERS,
  service_attachments: PermissionSubject.WORK_ORDERS,
  technicians: PermissionSubject.WORK_ORDERS,
  payments: PermissionSubject.BILLING,
  recurring_invoices: PermissionSubject.BILLING,
  recurring_parts: PermissionSubject.BILLING,
  recurring_labor: PermissionSubject.BILLING,
  quotes: PermissionSubject.QUOTES,
  quote_parts: PermissionSubject.QUOTES,
  quote_labor: PermissionSubject.QUOTES,
  quote_attachments: PermissionSubject.QUOTES,
  inspection_quote_requests: PermissionSubject.QUOTES,
  inventory_parts: PermissionSubject.INVENTORY,
  inspections: PermissionSubject.INSPECTIONS,
  inspection_items: PermissionSubject.INSPECTIONS,
  notifications: PermissionSubject.DASHBOARD,
}
