name: Support Request
description: Submit a request for assistance or inquiry about Torqvoice
title: "[Support]: "
labels: ["support"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Inquiry"
      description: "Please provide a detailed description of your inquiry, issue, or the assistance you require with Torqvoice."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "Please provide the Torqvoice version tag"
    validations:
      required: true
  - type: checkboxes
    id: deployment-type
    attributes:
      label: "Deployment Type"
      description: "Select the type of Torqvoice deployment you are using."
      options:
        - label: Docker
        - label: Standalone
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - Debian
        - Ubuntu
        - Other Linux
        - Windows
        - Other
    validations:
      required: false
  - type: dropdown
    id: browser
    attributes:
      label: "Browser"
      description: "Which browser are you using?"
      options:
        - Chrome
        - Firefox
        - Brave
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: "Any Other Information That May Be Helpful"
