/**
 * Where a workshop's WhatsApp setup lives in app settings.
 *
 * Provider credentials are namespaced by provider rather than enumerated, so a
 * new adapter brings its own fields without a change here, and switching
 * provider never overwrites the credentials of the old one.
 */

export const ORG_WHATSAPP_KEYS = {
  WHATSAPP_ENABLED: 'whatsapp.enabled',
  WHATSAPP_PROVIDER: 'whatsapp.provider',
  /** The workshop's own WhatsApp number, E.164. */
  WHATSAPP_FROM: 'whatsapp.from',
  /** Template used to reopen a conversation once the 24 hour window closed. */
  WHATSAPP_TEMPLATE_NAME: 'whatsapp.template.name',
  WHATSAPP_TEMPLATE_LANGUAGE: 'whatsapp.template.language',
  /** Ordered list of tokens filling the template's numbered placeholders. */
  WHATSAPP_TEMPLATE_VARIABLES: 'whatsapp.template.variables',
} as const

export type OrgWhatsappKey = (typeof ORG_WHATSAPP_KEYS)[keyof typeof ORG_WHATSAPP_KEYS]
export const ALL_ORG_WHATSAPP_KEYS = Object.values(ORG_WHATSAPP_KEYS)

const CREDENTIAL_PREFIX = 'whatsapp.cred.'

/** Setting key holding one credential field for one provider. */
export function whatsappCredentialKey(provider: string, field: string): string {
  return `${CREDENTIAL_PREFIX}${provider}.${field}`
}

/** Reads the field name back out, or null when the key is something else. */
export function parseWhatsappCredentialKey(key: string, provider: string): string | null {
  const prefix = `${CREDENTIAL_PREFIX}${provider}.`
  return key.startsWith(prefix) ? key.slice(prefix.length) : null
}

/**
 * Generated by us rather than pasted by the workshop, for providers that sign
 * nothing and rely on the webhook URL being unguessable.
 */
export const WHATSAPP_WEBHOOK_TOKEN_FIELD = 'webhookToken'
