/**
 * What a spreadsheet column can become.
 *
 * Every importable field is listed once here, with the header names it is
 * known by. The synonyms are matched after `normalizeHeader` has lowercased
 * the header, stripped accents and dropped everything that is not a letter or
 * digit, so `"E-mail"`, `"E-Mail 1 - Value"` and `"email"` all land on the
 * same key. The list is deliberately multilingual: a Polish shop's export says
 * "Nr rejestracyjny", a German one "Kennzeichen", a Norwegian one "Reg.nr",
 * and all of them are the licence plate.
 *
 * Keys are `<group>.<name>`. The group says which record the value belongs
 * to; an import of vehicles carries an optional owner, an import of service
 * history carries the vehicle and, optionally, the owner.
 */

export type ImportEntity = 'customers' | 'vehicles' | 'services'
export type FieldGroup = 'customer' | 'vehicle' | 'service'
export type FieldType =
  | 'text'
  | 'email'
  | 'phone'
  | 'date'
  | 'number'
  | 'integer'
  | 'year'
  | 'vin'
  | 'plate'
  | 'fuel'
  | 'transmission'

export interface ImportField {
  key: string
  group: FieldGroup
  type: FieldType
  /** Normalised header names this column is commonly called. */
  synonyms: readonly string[]
  /** Header used when we write a template file. */
  templateHeader: string
  /** Example value for the template file. */
  example: string
}

export const IMPORT_FIELDS: readonly ImportField[] = [
  // ── Customer ──────────────────────────────────────────────────────────────
  {
    key: 'customer.name',
    group: 'customer',
    type: 'text',
    templateHeader: 'Customer name',
    example: 'Example Customer',
    synonyms: [
      'name',
      'fullname',
      'customername',
      'customer',
      'contactname',
      'displayname',
      'clientname',
      'client',
      'owner',
      'ownername',
      'kunde',
      'kundename',
      'kundenname',
      'kundnavn',
      'kundenavn',
      'navn',
      'nombre',
      'nombrecompleto',
      'cliente',
      'nom',
      'nomcomplet',
      'nome',
      'nomecompleto',
      'nazwa',
      'klient',
      'imieinazwisko',
      'naam',
      'klant',
      'klantnaam',
      'musteri',
      'musteriadi',
      'adsoyad',
      'klientas',
      'vardaspavarde',
      'imya',
      'klient',
      'fio',
    ],
  },
  {
    key: 'customer.firstName',
    group: 'customer',
    type: 'text',
    templateHeader: 'First name',
    example: '',
    synonyms: [
      'firstname',
      'givenname',
      'first',
      'forename',
      'vorname',
      'fornavn',
      'fornamn',
      'prenom',
      'primernombre',
      'imie',
      'voornaam',
      'ad',
      'vardas',
      'primeironome',
    ],
  },
  {
    key: 'customer.lastName',
    group: 'customer',
    type: 'text',
    templateHeader: 'Last name',
    example: '',
    synonyms: [
      'lastname',
      'surname',
      'familyname',
      'last',
      'nachname',
      'familienname',
      'etternavn',
      'efternamn',
      'nomdefamille',
      'apellido',
      'apellidos',
      'cognome',
      'nazwisko',
      'achternaam',
      'soyad',
      'soyadi',
      'pavarde',
      'sobrenome',
      'familiya',
    ],
  },
  {
    key: 'customer.customerNumber',
    group: 'customer',
    type: 'text',
    templateHeader: 'Customer number',
    example: '1001',
    synonyms: [
      'customernumber',
      'customerno',
      'customerid',
      'clientnumber',
      'clientid',
      'accountnumber',
      'number',
      'kundennummer',
      'kundennr',
      'kundenr',
      'kundnummer',
      'numerocliente',
      'numeroclient',
      'nrklienta',
      'klantnummer',
      'musterino',
      'klientonumeris',
    ],
  },
  {
    key: 'customer.email',
    group: 'customer',
    type: 'email',
    templateHeader: 'Email',
    example: 'customer@example.com',
    synonyms: [
      'email',
      'emailaddress',
      'mail',
      'primaryemail',
      'emailaddress1',
      'email1',
      'email1value',
      'epost',
      'epostadresse',
      'correo',
      'correoelectronico',
      'courriel',
      'adresseemail',
      'emailadres',
      'eposta',
      'elpastas',
      'elektroninispastas',
      'pochta',
    ],
  },
  {
    key: 'customer.phone',
    group: 'customer',
    type: 'phone',
    templateHeader: 'Phone',
    example: '+1 202 555 0100',
    synonyms: [
      'phone',
      'phonenumber',
      'telephone',
      'tel',
      'mobile',
      'mobilenumber',
      'mobilephone',
      'cell',
      'cellphone',
      'primaryphone',
      'phone1',
      'phone1value',
      'mobilephone1',
      'telefon',
      'telefonnummer',
      'mobil',
      'mobilnummer',
      'handy',
      'telefono',
      'movil',
      'celular',
      'telephone',
      'portable',
      'cellulare',
      'telefoon',
      'mobiel',
      'telefonas',
      'mobilusis',
      'mobilnyj',
    ],
  },
  {
    key: 'customer.company',
    group: 'customer',
    type: 'text',
    templateHeader: 'Company',
    example: 'Example Company Ltd',
    synonyms: [
      'company',
      'companyname',
      'organization',
      'organisation',
      'organization1name',
      'businessname',
      'business',
      'org',
      'firma',
      'firmenname',
      'unternehmen',
      'selskap',
      'bedrift',
      'foretag',
      'empresa',
      'entreprise',
      'societe',
      'azienda',
      'societa',
      'bedrijf',
      'bedrijfsnaam',
      'sirket',
      'imone',
      'kompaniya',
    ],
  },
  {
    key: 'customer.address',
    group: 'customer',
    type: 'text',
    templateHeader: 'Address',
    example: '1 Example Street, Example City',
    synonyms: [
      'address',
      'fulladdress',
      'streetaddress',
      'mailingaddress',
      'homeaddress',
      'businessaddress',
      'address1formatted',
      'adresse',
      'anschrift',
      'direccion',
      'domicilio',
      'indirizzo',
      'adres',
      'endereco',
      'adresas',
      'ulica',
    ],
  },
  {
    key: 'customer.street',
    group: 'customer',
    type: 'text',
    templateHeader: 'Street',
    example: '',
    synonyms: [
      'street',
      'street1',
      'addressline1',
      'address1',
      'line1',
      'homestreet',
      'businessstreet',
      'strasse',
      'gate',
      'gateadresse',
      'calle',
      'rue',
      'via',
      'straat',
      'sokak',
      'gatve',
      'rua',
    ],
  },
  {
    key: 'customer.postalCode',
    group: 'customer',
    type: 'text',
    templateHeader: 'Postal code',
    example: '',
    synonyms: [
      'postalcode',
      'postcode',
      'zip',
      'zipcode',
      'homepostalcode',
      'businesspostalcode',
      'plz',
      'postleitzahl',
      'postnummer',
      'postnr',
      'codigopostal',
      'cp',
      'cap',
      'kodpocztowy',
      'postalcode',
      'postakodu',
      'pastokodas',
      'cep',
    ],
  },
  {
    key: 'customer.city',
    group: 'customer',
    type: 'text',
    templateHeader: 'City',
    example: '',
    synonyms: [
      'city',
      'town',
      'homecity',
      'businesscity',
      'stadt',
      'ort',
      'poststed',
      'sted',
      'by',
      'ciudad',
      'ville',
      'citta',
      'miasto',
      'plaats',
      'woonplaats',
      'sehir',
      'il',
      'miestas',
      'cidade',
      'gorod',
    ],
  },
  {
    key: 'customer.state',
    group: 'customer',
    type: 'text',
    templateHeader: 'State',
    example: '',
    synonyms: [
      'state',
      'province',
      'region',
      'county',
      'bundesland',
      'fylke',
      'provincia',
      'estado',
    ],
  },
  {
    key: 'customer.country',
    group: 'customer',
    type: 'text',
    templateHeader: 'Country',
    example: '',
    synonyms: ['country', 'land', 'pais', 'pays', 'paese', 'kraj', 'ulke', 'salis', 'strana'],
  },
  {
    key: 'customer.taxId',
    group: 'customer',
    type: 'text',
    templateHeader: 'Tax ID',
    example: '',
    synonyms: [
      'taxid',
      'taxnumber',
      'vat',
      'vatnumber',
      'vatid',
      'orgnr',
      'orgnumber',
      'organisationsnummer',
      'organisasjonsnummer',
      'ustid',
      'ustidnr',
      'steuernummer',
      'nif',
      'cif',
      'rfc',
      'siret',
      'siren',
      'tva',
      'partitaiva',
      'piva',
      'nip',
      'btwnummer',
      'kvk',
      'vergino',
      'pvmkodas',
      'cnpj',
      'cpf',
      'inn',
      'ein',
      'abn',
    ],
  },
  {
    key: 'customer.notes',
    group: 'customer',
    type: 'text',
    templateHeader: 'Customer notes',
    example: '',
    synonyms: [
      'notes',
      'note',
      'customernotes',
      'privatenotes',
      'comments',
      'comment',
      'remarks',
      'notizen',
      'bemerkung',
      'notater',
      'merknad',
      'notas',
      'observaciones',
      'commentaires',
      'uwagi',
      'notities',
      'opmerkingen',
      'notlar',
      'pastabos',
      'primechaniya',
    ],
  },

  // ── Vehicle ───────────────────────────────────────────────────────────────
  {
    key: 'vehicle.description',
    group: 'vehicle',
    type: 'text',
    templateHeader: 'Vehicle',
    example: '',
    synonyms: [
      'vehicle',
      'vehicledescription',
      'vehiclename',
      'car',
      'makemodel',
      'makeandmodel',
      'yearmakemodel',
      'fahrzeug',
      'kjoretoy',
      'bil',
      'vehiculo',
      'coche',
      'vehicule',
      'voiture',
      'veicolo',
      'pojazd',
      'voertuig',
      'auto',
      'arac',
      'transportopriemone',
      'automobilis',
      'veiculo',
      'avtomobil',
    ],
  },
  {
    key: 'vehicle.make',
    group: 'vehicle',
    type: 'text',
    templateHeader: 'Make',
    example: 'Toyota',
    synonyms: [
      'make',
      'manufacturer',
      'brand',
      'vehiclemake',
      'marke',
      'hersteller',
      'merke',
      'fabrikat',
      'marca',
      'marque',
      'marka',
      'merk',
      'marke',
      'gamintojas',
    ],
  },
  {
    key: 'vehicle.model',
    group: 'vehicle',
    type: 'text',
    templateHeader: 'Model',
    example: 'Corolla',
    synonyms: ['model', 'vehiclemodel', 'modell', 'modelo', 'modele', 'modello', 'modelis'],
  },
  {
    key: 'vehicle.year',
    group: 'vehicle',
    type: 'year',
    templateHeader: 'Year',
    example: '2018',
    synonyms: [
      'year',
      'modelyear',
      'vehicleyear',
      'yearofmanufacture',
      'baujahr',
      'modelljahr',
      'arsmodell',
      'argang',
      'ano',
      'anno',
      'annee',
      'rok',
      'rocznik',
      'bouwjaar',
      'jaar',
      'yil',
      'modelyili',
      'metai',
      'god',
      'godvypuska',
    ],
  },
  {
    key: 'vehicle.vin',
    group: 'vehicle',
    type: 'vin',
    templateHeader: 'VIN',
    example: '1HGBH41JXMN109186',
    synonyms: [
      'vin',
      'vinnumber',
      'chassis',
      'chassisnumber',
      'chassisno',
      'serial',
      'serialnumber',
      'fahrgestellnummer',
      'fin',
      'understellsnummer',
      'chassisnr',
      'bastidor',
      'numerodebastidor',
      'numerodechassis',
      'telaio',
      'numerotelaio',
      'nrvin',
      'numervin',
      'chassisnummer',
      'sasino',
      'sasinumarasi',
      'kebulonumeris',
      'nomerkuzova',
    ],
  },
  {
    key: 'vehicle.licensePlate',
    group: 'vehicle',
    type: 'plate',
    templateHeader: 'License plate',
    example: 'ABC 123',
    synonyms: [
      'licenseplate',
      'licenceplate',
      'plate',
      'platenumber',
      'registration',
      'registrationnumber',
      'regnumber',
      'regno',
      'reg',
      'tag',
      'numberplate',
      'kennzeichen',
      'kfzkennzeichen',
      'nummernschild',
      'regnr',
      'registreringsnummer',
      'skilt',
      'kjennemerke',
      'matricula',
      'placa',
      'patente',
      'immatriculation',
      'plaque',
      'targa',
      'nrrejestracyjny',
      'numerrejestracyjny',
      'rejestracja',
      'kenteken',
      'plaka',
      'valstybinisnumeris',
      'gosnomer',
      'nomernoyznak',
    ],
  },
  {
    key: 'vehicle.color',
    group: 'vehicle',
    type: 'text',
    templateHeader: 'Color',
    example: 'Silver',
    synonyms: [
      'color',
      'colour',
      'farbe',
      'farge',
      'couleur',
      'colore',
      'kolor',
      'kleur',
      'renk',
      'spalva',
      'cor',
      'cvet',
    ],
  },
  {
    key: 'vehicle.mileage',
    group: 'vehicle',
    type: 'integer',
    templateHeader: 'Mileage',
    example: '84500',
    synonyms: [
      'mileage',
      'odometer',
      'odo',
      'km',
      'kilometers',
      'kilometres',
      'miles',
      'currentmileage',
      'kilometerstand',
      'kmstand',
      'laufleistung',
      'kilometerstand',
      'kmstand',
      'kjorelengde',
      'kilometraje',
      'kilometrage',
      'chilometraggio',
      'przebieg',
      'kilometrazas',
      'rida',
      'probeg',
      'quilometragem',
    ],
  },
  {
    key: 'vehicle.fuelType',
    group: 'vehicle',
    type: 'fuel',
    templateHeader: 'Fuel',
    example: 'gasoline',
    synonyms: [
      'fuel',
      'fueltype',
      'kraftstoff',
      'kraftstoffart',
      'antrieb',
      'drivstoff',
      'combustible',
      'carburant',
      'carburante',
      'alimentazione',
      'paliwo',
      'rodzajpaliwa',
      'brandstof',
      'yakit',
      'kuras',
      'toplivo',
      'combustivel',
    ],
  },
  {
    key: 'vehicle.transmission',
    group: 'vehicle',
    type: 'transmission',
    templateHeader: 'Transmission',
    example: 'automatic',
    synonyms: [
      'transmission',
      'gearbox',
      'getriebe',
      'girkasse',
      'transmision',
      'cambio',
      'boitedevitesses',
      'skrzyniabiegow',
      'versnellingsbak',
      'vites',
      'sanziman',
      'pavaru deze',
      'korobka',
    ],
  },
  {
    key: 'vehicle.engineSize',
    group: 'vehicle',
    type: 'text',
    templateHeader: 'Engine',
    example: '1.8',
    synonyms: [
      'engine',
      'enginesize',
      'displacement',
      'motor',
      'hubraum',
      'motorstorrelse',
      'cilindrada',
      'cylindree',
      'cilindrata',
      'pojemnosc',
      'motorinhoud',
      'motorhacmi',
      'variklis',
      'dvigatel',
    ],
  },
  {
    key: 'vehicle.engineCode',
    group: 'vehicle',
    type: 'text',
    templateHeader: 'Engine code',
    example: '',
    synonyms: [
      'enginecode',
      'motorcode',
      'motorkode',
      'codigomotor',
      'codemoteur',
      'codicemotore',
      'kodsilnika',
    ],
  },
  {
    key: 'vehicle.purchaseDate',
    group: 'vehicle',
    type: 'date',
    templateHeader: 'Purchase date',
    example: '',
    synonyms: [
      'purchasedate',
      'datepurchased',
      'boughton',
      'firstregistration',
      'registrationdate',
      'kaufdatum',
      'erstzulassung',
      'kjopsdato',
      'forstegangsregistrert',
      'fechacompra',
      'dateachat',
      'dataacquisto',
      'datazakupu',
      'aankoopdatum',
      'satinalmatarihi',
      'pirkimodata',
    ],
  },
  {
    key: 'vehicle.purchasePrice',
    group: 'vehicle',
    type: 'number',
    templateHeader: 'Purchase price',
    example: '',
    synonyms: [
      'purchaseprice',
      'kaufpreis',
      'kjopspris',
      'preciocompra',
      'prixachat',
      'prezzoacquisto',
      'cenazakupu',
      'aankoopprijs',
    ],
  },

  // ── Service history ───────────────────────────────────────────────────────
  {
    key: 'service.date',
    group: 'service',
    type: 'date',
    templateHeader: 'Service date',
    example: '2024-03-15',
    synonyms: [
      'date',
      'servicedate',
      'dateofservice',
      'invoicedate',
      'workorderdate',
      'jobdate',
      'completed',
      'completeddate',
      'datum',
      'servicedatum',
      'rechnungsdatum',
      'dato',
      'servicedato',
      'fakturadato',
      'fecha',
      'fechaservicio',
      'fechafactura',
      'datefacture',
      'data',
      'dataservizio',
      'datafattura',
      'datauslugi',
      'datafaktury',
      'tarih',
      'servistarihi',
    ],
  },
  {
    key: 'service.title',
    group: 'service',
    type: 'text',
    templateHeader: 'Service',
    example: 'Oil change and inspection',
    synonyms: [
      'service',
      'title',
      'servicetitle',
      'job',
      'jobname',
      'jobtitle',
      'workorder',
      'worktype',
      'subject',
      'summary',
      'arbeit',
      'leistung',
      'titel',
      'arbeid',
      'tittel',
      'trabajo',
      'titulo',
      'travail',
      'titre',
      'lavoro',
      'titolo',
      'usluga',
      'tytul',
      'werk',
      'hizmet',
      'baslik',
      'darbas',
      'paslauga',
    ],
  },
  {
    key: 'service.description',
    group: 'service',
    type: 'text',
    templateHeader: 'Description',
    example: 'Replaced oil and filter, checked brakes',
    synonyms: [
      'description',
      'details',
      'workdone',
      'workperformed',
      'workdescription',
      'linedescription',
      'beschreibung',
      'beskrivelse',
      'descripcion',
      'descriptif',
      'descrizione',
      'opis',
      'omschrijving',
      'beschrijving',
      'aciklama',
      'aprasymas',
      'opisanie',
      'descricao',
    ],
  },
  {
    key: 'service.total',
    group: 'service',
    type: 'number',
    templateHeader: 'Total',
    example: '189.50',
    synonyms: [
      'total',
      'amount',
      'cost',
      'price',
      'totalamount',
      'grandtotal',
      'invoicetotal',
      'totalcost',
      'sum',
      'betrag',
      'gesamt',
      'gesamtbetrag',
      'summe',
      'kosten',
      'preis',
      'belop',
      'totalt',
      'totalbelop',
      'pris',
      'importe',
      'montant',
      'totale',
      'importo',
      'kwota',
      'suma',
      'razem',
      'bedrag',
      'totaal',
      'tutar',
      'toplam',
      'suma',
      'itogo',
      'valor',
    ],
  },
  {
    key: 'service.mileage',
    group: 'service',
    type: 'integer',
    templateHeader: 'Mileage at service',
    example: '84500',
    synonyms: [
      'servicemileage',
      'mileageatservice',
      'odometeratservice',
      'kmstandservice',
      'kmveditjeneste',
    ],
  },
  {
    key: 'service.invoiceNumber',
    group: 'service',
    type: 'text',
    templateHeader: 'Invoice number',
    example: 'INV-1042',
    synonyms: [
      'invoicenumber',
      'invoiceno',
      'invoice',
      'invoiceid',
      'workordernumber',
      'ronumber',
      'ro',
      'rechnungsnummer',
      'rechnungsnr',
      'fakturanummer',
      'fakturanr',
      'numerofactura',
      'factura',
      'numerofacture',
      'facture',
      'numerofattura',
      'fattura',
      'nrfaktury',
      'numerfaktury',
      'factuurnummer',
      'faturano',
      'saskaitosnumeris',
      'nomerscheta',
    ],
  },
  {
    key: 'service.notes',
    group: 'service',
    type: 'text',
    templateHeader: 'Service notes',
    example: '',
    synonyms: [
      'servicenotes',
      'jobnotes',
      'internalnotes',
      'technotes',
      'technicalnotes',
      'diagnosticnotes',
      'workordernotes',
    ],
  },
  {
    key: 'service.technician',
    group: 'service',
    type: 'text',
    templateHeader: 'Technician',
    example: '',
    synonyms: [
      'technician',
      'tech',
      'mechanic',
      'techniker',
      'mechaniker',
      'tekniker',
      'mekaniker',
      'tecnico',
      'technicien',
      'mecanicien',
      'meccanico',
      'mechanik',
      'monteur',
      'teknisyen',
      'mechanikas',
      'mekhanik',
    ],
  },
]

const BY_KEY = new Map(IMPORT_FIELDS.map((f) => [f.key, f]))

export function fieldByKey(key: string): ImportField | undefined {
  return BY_KEY.get(key)
}

/** Which groups an entity's mapping can carry. */
export function groupsFor(entity: ImportEntity): FieldGroup[] {
  switch (entity) {
    case 'customers':
      return ['customer']
    case 'vehicles':
      return ['vehicle', 'customer']
    case 'services':
      return ['service', 'vehicle', 'customer']
  }
}

export function fieldsFor(entity: ImportEntity): ImportField[] {
  const groups = new Set(groupsFor(entity))
  return IMPORT_FIELDS.filter((f) => groups.has(f.group))
}

/**
 * Fields the template file carries per entity. The service template also
 * names the vehicle and its owner, since that is how a history export from a
 * shop system looks: one row per job, with the car and the customer alongside.
 */
export function templateFieldsFor(entity: ImportEntity): ImportField[] {
  const wanted: Record<ImportEntity, string[]> = {
    customers: [
      'customer.name',
      'customer.email',
      'customer.phone',
      'customer.company',
      'customer.address',
      'customer.customerNumber',
      'customer.taxId',
      'customer.notes',
    ],
    vehicles: [
      'vehicle.make',
      'vehicle.model',
      'vehicle.year',
      'vehicle.licensePlate',
      'vehicle.vin',
      'vehicle.mileage',
      'vehicle.color',
      'vehicle.fuelType',
      'vehicle.transmission',
      'vehicle.engineSize',
      'customer.name',
      'customer.email',
      'customer.phone',
    ],
    services: [
      'service.date',
      'service.title',
      'service.description',
      'service.total',
      'service.mileage',
      'service.invoiceNumber',
      'vehicle.licensePlate',
      'vehicle.vin',
      'vehicle.make',
      'vehicle.model',
      'vehicle.year',
      'customer.name',
      'customer.email',
      'customer.phone',
    ],
  }
  return wanted[entity].map((k) => BY_KEY.get(k)).filter((f): f is ImportField => Boolean(f))
}
